# Generated by Django 4.2.5 on 2023-09-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='crreated_at',
            new_name='created_at',
        ),
    ]
