# Generated by Django 3.2.12 on 2023-09-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(max_length=100),
        ),
    ]
